#!/bin/bash

###############################################################################
# WARNING
# This is a symlinked file. The original lives at hooks/build in this repository
###############################################################################

# original docker build command
echo "overwriting docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME ."

cat "../mvn-versions.txt" | while read mvn_version
do
    cat "../gradle-versions.txt" | while read gradle_version
    do
        # The new image tag will include the version of our software, prefixed to the os image we're currently building
        IMAGE_TAG="${DOCKER_REPO}:8-jdk-alpine-mvn-${mvn_version}-gradle${gradle_version}"

        echo "docker build -f Dockerfile --build-arg MAVEN_VERSION=${mvn_version}  --build-arg GRADLE_VERSION=${gradle_version} -t ${IMAGE_TAG} ."
        docker build -f Dockerfile --build-arg MAVEN_VERSION=${mvn_version}  --build-arg GRADLE_VERSION=${gradle_version} -t ${IMAGE_TAG} .
    done
done
