#!/bin/bash

###############################################################################
# WARNING
# This is a symlinked file. The original lives at hooks/build in this repository
###############################################################################

# original docker build command
echo "overwriting docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME ."

for mvn_version in 3.5.4 3.6.3 
do
    for gradle_version in 6.8.3 6.8.2 6.8.1 6.8
    do
        # The new image tag will include the version of our software, prefixed to the os image we're currently building
        IMAGE_TAG="${DOCKER_REPO}:8-jdk-alpine-mvn-${mvn_version}-gradle-${gradle_version}"

        echo "docker build -f Dockerfile --build-arg MAVEN_VERSION=${mvn_version}  --build-arg GRADLE_VERSION=${gradle_version} -t ${IMAGE_TAG} ."
        docker build -f Dockerfile --build-arg MAVEN_VERSION=${mvn_version}  --build-arg GRADLE_VERSION=${gradle_version} -t ${IMAGE_TAG} .
    done
done
