#!/bin/bash

###############################################################################
# WARNING
# This is a symlinked file. The original lives at hooks/push in this repository
###############################################################################

# original docker push command
echo "overwriting docker push $IMAGE_NAME"

cat "../mvn-versions.txt" | while read mvn_version
do
    cat "../gradle-versions.txt" | while read gradle_version
    do
        # The new image tag will include the version of our software, prefixed to the os image we're currently building
        IMAGE_TAG="${DOCKER_REPO}:8-jdk-alpine-mvn-${mvn_version}-gradle${gradle_version}"

        echo "docker push ${IMAGE_TAG}"
        docker push ${IMAGE_TAG}
    done
done
